#!/bin/bash

if [ -z "$1" ]; then
	echo "need argument"
	exit 1
fi

NAME="$1"

# TODO: refresh command to recreate stopped container with new mounts?

export SESSION_DIR="$HOME/.local/share/ccmux/sessions/$NAME"

# name = ID
# bashcompletion is files in :this: dir
# symlink normalname and normalname.shardid.p1
# also symlink to normal names

mkdir -p "$SESSION_DIR"

NEWHISTFILE=$SESSION_DIR/bash_history
NEWKUBECONFIG=$SESSION_DIR/kubeconfig

touch $NEWKUBECONFIG $NEWHISTFILE

# todo: prompt based on the contents of KUBECONFIG; fallback to $NAME if lacking?
exec bash --rcfile <(echo ". ~/.bashrc; HISTFILE=$NEWHISTFILE; export KUBECONFIG=$NEWKUBECONFIG; export PS1='[\W \[\e[32m\]$NAME\[\e[m\]]\$ '")

